import {
    ContoursDataLabelProvider,
    DpiHelper,
    EDataLabelProviderType,
    ENumericFormat,
    formatNumber,
    IBaseDataLabelProviderOptions,
    IContourDrawingParams,
    parseColorToUIntArgb,
    Point,
    Rect,
    RenderPassData,
    TDataLabel,
    UniformContoursRenderableSeries,
    UniformHeatmapDataSeries,
    WebGlRenderContext2D
} from "scichart";

import type { TContourPolyline } from "./contourTracer";
import { traceContours } from "./contourTracer";

type TFont = ReturnType<WebGlRenderContext2D["getFont"]>;
type TTextBounds = Parameters<TFont["CalculateStringBounds"]>[1];

/** One contour line traced and prepared for labelling. @ignore */
type TLabelledTrace = {
    level: number;
    text: string;
    /** Flat `[x0, y0, x1, y1, ...]` pixel coordinates of the whole polyline */
    points: number[];
    /** Cumulative pixel arc length, one entry per point */
    pixelLengths: number[];
    /** Cumulative arc length in grid-index space. Invariant under pan and zoom */
    indexLengths: number[];
    totalPixel: number;
    totalIndex: number;
    /** Index-space arc positions to place labels at, most wanted first */
    anchors: number[];
};

/** Cells smaller than this many pixels are subsampled when tracing - the error is invisible. @ignore */
const MIN_TRACE_CELL_PIXELS = 2;
/** Upper bound on the cells visited per trace, so huge grids cannot stall the frame. @ignore */
const MAX_TRACE_CELLS = 100_000;
/**
 * Largest anchor lattice, as a power of two. Anchors sit at k / anchorCount along a contour, so this
 * bounds how finely a single line can be subdivided.
 * @ignore
 */
const MAX_ANCHOR_LEVEL = 10;

type TContourLevel = { level: number; isMajor: boolean };

/** Returns the levels generated by the contour shader without changing the SciChart library. */
const getContourLevels = (
    series: UniformContoursRenderableSeries,
    contourParams: IContourDrawingParams
): TContourLevel[] => {
    if (contourParams.zLevels?.length) {
        return contourParams.zLevels
            .slice()
            .sort((left, right) => left - right)
            .map(level => ({ level, isMajor: true }));
    }

    const { zMin, zMax, zOffset, majorStepZ, minorStepZ, dataZRange } = contourParams;
    const normMin = series.colorMap?.minimum ?? dataZRange.min;
    const normMax = series.colorMap?.maximum ?? dataZRange.max;
    const normDiff = normMax - normMin;
    const zDiff = zMax - zMin;
    if (!(normDiff > 0) || !(zDiff > 0) || !(majorStepZ > 0) || !(minorStepZ > 0)) return [];

    const base = normMin + (zOffset / zDiff) * normDiff;
    const minorsPlusOne = Math.max(1, Math.round(majorStepZ / minorStepZ));
    const first = Math.ceil((zMin - base) / minorStepZ - 0.0001);
    const last = Math.floor((zMax - base) / minorStepZ + 0.0001);
    const levels: TContourLevel[] = [];
    for (let index = first; index <= last; index++) {
        levels.push({
            level: base + index * minorStepZ,
            isMajor: ((index % minorsPlusOne) + minorsPlusOne) % minorsPlusOne === 0
        });
    }
    return levels;
};

export interface IAlongLineContoursDataLabelProviderOptions extends IBaseDataLabelProviderOptions {
    /**
     * Gets or sets numeric format to use for formatting values to text. For a list of values, see {@link ENumericFormat}
     */
    numericFormat?: ENumericFormat;
    /**
     * Gets or sets the precision to use when formatting values to text.
     */
    precision?: number;
    /** Flag to enable/disable dataLabel generation.  Default true */
    isEnabled?: boolean;
    /**
     * Sets the target distance in pixels between consecutive labels on the same contour line.
     * Larger values mean fewer, more widely spaced labels. Default 180
     * @remarks
     * This is a target, not an exact spacing. A line is divided into a power-of-two number of equal
     * parts, so labels on it are evenly spaced but the spacing lands within about a factor of 1.4 of
     * the value set here. Only doubling the division keeps existing labels where they are, which is
     * what stops them jumping while the chart is zoomed.
     */
    labelSpacing?: number;
    /**
     * When true, each label is rotated to follow the contour line it sits on. Default true
     */
    rotateToLine?: boolean;
    /**
     * When true, a label which would overlap an already placed label is dropped. Default true
     */
    avoidOverlaps?: boolean;
    /**
     * Sets the maximum number of labels placed on the visible part of a single contour line.
     * Default 12
     * @remarks
     * A ceiling, not a target. Because a line is always divided into a power-of-two number of equal
     * parts, the count actually used is the largest of 1, 3, 7, 15, ... which fits under this value -
     * so 12 behaves as 7. Anything in between would have to space the labels unevenly.
     */
    maxLabelsPerLine?: number;
    /**
     * When true, contour lines drawn with the minorLineStyle are labelled too. Only has an effect
     * when the parent series has minorsPerMajor > 0. Default false
     */
    labelMinorContours?: boolean;
}
export class AlongLineContoursDataLabelProvider extends ContoursDataLabelProvider {
    public readonly type: EDataLabelProviderType = EDataLabelProviderType.Contours;
    private labelSpacingProperty: number = 180;
    private rotateToLineProperty: boolean = true;
    private avoidOverlapsProperty: boolean = true;
    private maxLabelsPerLineProperty: number = 12;
    private labelMinorContoursProperty: boolean = false;
    /** Signature of the inputs {@link polylineCache} was traced from, see getPolylines */
    private polylineCacheKey: string;
    private polylineCache: TContourPolyline[] = [];

    public constructor(options?: IAlongLineContoursDataLabelProviderOptions) {
        super(options);
        this.numericFormat = options?.numericFormat ?? this.numericFormat;
        this.precision = options?.precision ?? this.precision;
        this.isEnabled = options?.isEnabled ?? this.isEnabled;
        this.labelSpacingProperty = options?.labelSpacing ?? this.labelSpacingProperty;
        this.rotateToLineProperty = options?.rotateToLine ?? this.rotateToLineProperty;
        this.avoidOverlapsProperty = options?.avoidOverlaps ?? this.avoidOverlapsProperty;
        this.maxLabelsPerLineProperty = options?.maxLabelsPerLine ?? this.maxLabelsPerLineProperty;
        this.labelMinorContoursProperty = options?.labelMinorContours ?? this.labelMinorContoursProperty;
    }

    /**
     * Gets or sets the target distance in pixels between consecutive labels on the same contour line.
     * Default 180. See {@link IAlongLineContoursDataLabelProviderOptions.labelSpacing} on why this is a target
     * rather than an exact spacing.
     */
    public get labelSpacing() {
        return this.labelSpacingProperty;
    }
    public set labelSpacing(value: number) {
        this.labelSpacingProperty = value;
        this.invalidateParent();
    }

    /**
     * Gets or sets whether each label is rotated to follow the contour line it sits on. Default true
     */
    public get rotateToLine() {
        return this.rotateToLineProperty;
    }
    public set rotateToLine(value: boolean) {
        this.rotateToLineProperty = value;
        this.invalidateParent();
    }

    /**
     * Gets or sets whether a label which would overlap an already placed label is dropped. Default true
     */
    public get avoidOverlaps() {
        return this.avoidOverlapsProperty;
    }
    public set avoidOverlaps(value: boolean) {
        this.avoidOverlapsProperty = value;
        this.invalidateParent();
    }

    /**
     * Gets or sets the maximum number of labels placed on the visible part of a single contour line.
     * Default 12. This is a ceiling which is rounded down to one of 1, 3, 7, 15, ... - see
     * {@link IAlongLineContoursDataLabelProviderOptions.maxLabelsPerLine}
     */
    public get maxLabelsPerLine() {
        return this.maxLabelsPerLineProperty;
    }
    public set maxLabelsPerLine(value: number) {
        this.maxLabelsPerLineProperty = value;
        this.invalidateParent();
    }

    /**
     * Gets or sets whether contour lines drawn with the minorLineStyle are labelled too. Default false
     */
    public get labelMinorContours() {
        return this.labelMinorContoursProperty;
    }
    public set labelMinorContours(value: boolean) {
        this.labelMinorContoursProperty = value;
        this.invalidateParent();
    }

    public generateDataLabels(renderContext: WebGlRenderContext2D, renderPassData: RenderPassData): void {
        // clear any previous labels
        this.dataLabels = [];
        if (!this.isEnabled || !this.style || !this.style.fontFamily || !this.style.fontSize) {
            return;
        }
        this.dataSeries = this.parentSeries.dataSeries as unknown as UniformHeatmapDataSeries;
        if (!this.dataSeries) {
            return;
        }
        this.zValues = this.dataSeries.getZValues();

        const bounds = this.textBounds;
        const dpiAdjustedStyle = DpiHelper.adjustTextStyle(this.style);
        const font = renderContext.getFont(dpiAdjustedStyle, this.useRotation);

        this.colorValue = parseColorToUIntArgb(this.color);

        const series = this.parentSeries as unknown as UniformContoursRenderableSeries;
        const contourParams = series.getContourDrawingParams();

        this.makeAlongLineLabels(contourParams, renderPassData, font, bounds);
    }

    /**
     * Places labels along each traced contour line, rotated to follow the line, in the manner of
     * Plotly or matplotlib's clabel.
     * @remarks
     * Positions come from a nested lattice measured in *grid-index* arc length, which does not move
     * when the chart is panned or zoomed. {@link labelSpacing} only selects how far down the lattice
     * to go. Both refining the lattice and asking for more labels therefore *add* positions without
     * disturbing the ones already there, which is what keeps labels from jittering during a zoom.
     */
    public makeAlongLineLabels(
        contourParams: IContourDrawingParams,
        renderPassData: RenderPassData,
        font: TFont,
        bounds: TTextBounds
    ) {
        const dataSeries = this.dataSeries as UniformHeatmapDataSeries;
        const arrayWidth = dataSeries.arrayWidth;
        const arrayHeight = dataSeries.arrayHeight;
        if (arrayWidth < 2 || arrayHeight < 2) return;

        const levels = getContourLevels(this.parentSeries as unknown as UniformContoursRenderableSeries, contourParams)
            .filter(({ isMajor }) => isMajor || this.labelMinorContours)
            .map(({ level }) => level);
        if (levels.length === 0) return;

        const { xCoordinateCalculator: xCalc, yCoordinateCalculator: yCalc, isVerticalChart } = renderPassData;
        // The contour surface is a texture stretched over [xMin, xMax] x [yMin, yMax], with its texels -
        // the data samples - at the centre of each heatmap cell. Mapping grid indices to pixels the same
        // way places labels exactly on the drawn lines, whatever the axis type.
        const xStartPx = xCalc.getCoordinate(contourParams.xMin);
        const yStartPx = yCalc.getCoordinate(contourParams.yMin);
        const perColumn = (xCalc.getCoordinate(contourParams.xMax) - xStartPx) / arrayWidth;
        const perRow = (yCalc.getCoordinate(contourParams.yMax) - yStartPx) / arrayHeight;

        const stride = getTraceStride(arrayWidth, arrayHeight, perColumn, perRow);
        const polylines = this.getPolylines(dataSeries, levels, stride);
        if (polylines.length === 0) return;

        const seriesViewRect = this.parentSeries.parentSurface.seriesViewRect;
        const viewWidth = seriesViewRect.width;
        const viewHeight = seriesViewRect.height;
        const spacing = Math.max(1, this.labelSpacing) * DpiHelper.PIXEL_RATIO;
        const lineSpacing = this.getLineSpacing();
        const maxPerLine = Math.max(1, this.maxLabelsPerLine);

        const traces: TLabelledTrace[] = [];
        for (const polyline of polylines) {
            const text = formatNumber(
                polyline.level,
                this.numericFormat ?? ENumericFormat.Decimal,
                this.precision ?? 1
            );
            if (!text) continue;
            font.CalculateStringBounds(text, bounds, lineSpacing);
            const source = polyline.points;
            const points: number[] = new Array(source.length);
            for (let index = 0; index < source.length; index += 2) {
                const axisX = xStartPx + (source[index] + 0.5) * perColumn;
                const axisY = yStartPx + (source[index + 1] + 0.5) * perRow;
                points[index] = isVerticalChart ? axisY : axisX;
                points[index + 1] = isVerticalChart ? axisX : axisY;
            }
            const trace = buildTrace(
                polyline,
                points,
                text,
                bounds.m_fWidth,
                viewWidth,
                viewHeight,
                spacing,
                maxPerLine
            );
            if (trace) traces.push(trace);
        }
        if (traces.length === 0) return;

        // Ordered by index-space length, which does not change with zoom, so the order in which
        // lines claim space against each other is the same on every frame.
        traces.sort((left, right) => right.totalIndex - left.totalIndex || left.level - right.level);
        const maxAnchors = traces.reduce((max, trace) => Math.max(max, trace.anchors.length), 0);
        const placedRects: Rect[] = [];
        for (let round = 0; round < maxAnchors; round++) {
            for (const trace of traces) {
                if (round >= trace.anchors.length) continue;
                const label = this.placeAnchorLabel(
                    trace,
                    trace.anchors[round],
                    font,
                    bounds,
                    lineSpacing,
                    placedRects,
                    renderPassData
                );
                if (label) {
                    placedRects.push(label.rect);
                    this.dataLabels.push(label);
                }
            }
        }
    }

    /** @inheritDoc */
    public onDetach() {
        this.polylineCacheKey = undefined;
        this.polylineCache = [];
        this.dataSeries = undefined;
        this.zValues = undefined;
        super.onDetach();
    }

    /** Rotated labels need the alternative, transformable font instance. @inheritDoc */
    protected get useRotation(): boolean {
        return this.rotateToLine;
    }

    /**
     * Builds a label centred on (centreX, centreY), rotated by rotationAngle radians about that point.
     * `rect` is the axis aligned bounding box of the rotated text, so it can be used for overlap and
     * clipping tests.
     */
    protected createLabel(
        text: string,
        centreX: number,
        centreY: number,
        rotationAngle: number,
        font: TFont,
        bounds: TTextBounds,
        lineSpacing: number,
        dataX: number,
        dataY: number,
        color: number
    ): TDataLabel {
        font.CalculateStringBounds(text ?? "", bounds, lineSpacing);
        const textWidth = bounds.m_fWidth;
        const textHeight = bounds.m_fHeight;
        const lineBounds = bounds.GetLineBounds(0);
        const firstLineHeight = lineBounds.m_fHeight;
        lineBounds.delete();

        const left = centreX - textWidth / 2;
        const top = centreY - textHeight / 2;
        // position.y is the alphabetic baseline of the first line, not the top of the text
        const position = new Point(left, top + firstLineHeight);
        const rotationCenter = new Point(centreX, centreY);
        const unrotated = new Rect(left, top, textWidth, textHeight);

        return {
            text,
            position,
            rect: rotationAngle === 0 ? unrotated : getRotatedBoundingBox(unrotated, rotationCenter, rotationAngle),
            color,
            dataX,
            dataY,
            rotationAngle,
            rotationCenter
        };
    }

    /**
     * Builds the label for one anchor on a traced contour line, or nothing if it would leave the
     * series view rect or collide with an already placed label.
     * @param anchorIndexArc the anchor's position along the line, in grid-index arc length
     * @remarks
     * The label goes exactly on its anchor. There is deliberately no search for a nearby straighter
     * spot: whether such a search accepts or rejects a position flips as the line's curvature changes
     * under zoom, which showed up as labels hopping back and forth.
     */
    private placeAnchorLabel(
        trace: TLabelledTrace,
        anchorIndexArc: number,
        font: TFont,
        bounds: TTextBounds,
        lineSpacing: number,
        placedRects: Rect[],
        renderPassData: RenderPassData
    ): TDataLabel | undefined {
        font.CalculateStringBounds(trace.text, bounds, lineSpacing);
        const halfWidth = bounds.m_fWidth / 2;
        const seriesViewRect = this.parentSeries.parentSurface.seriesViewRect;

        // The anchor is defined in index space; convert to the matching point and pixel arc position
        const { segment, t } = locateArc(trace.indexLengths, anchorIndexArc);
        const centre = pointOnSegment(trace.points, segment, t);
        const pixelArc =
            trace.pixelLengths[segment] + t * (trace.pixelLengths[segment + 1] - trace.pixelLengths[segment]);

        // Chord under the text gives the tangent, clamped to the ends of the line
        const from = Math.max(0, Math.min(pixelArc - halfWidth, trace.totalPixel - 2 * halfWidth));
        const start = interpolateAlong(trace.points, trace.pixelLengths, Math.max(0, from));
        const end = interpolateAlong(
            trace.points,
            trace.pixelLengths,
            Math.min(trace.totalPixel, from + 2 * halfWidth)
        );
        const dx = end.x - start.x;
        const dy = end.y - start.y;
        if (dx === 0 && dy === 0) return undefined;

        // Screen y grows downwards, and DrawStringAdvanced takes a counter-clockwise angle
        let rotationAngle = this.rotateToLine ? -Math.atan2(dy, dx) : 0;
        // Keep text upright rather than mirrored
        if (rotationAngle > Math.PI / 2) rotationAngle -= Math.PI;
        else if (rotationAngle < -Math.PI / 2) rotationAngle += Math.PI;

        const label = this.createLabel(
            trace.text,
            centre.x,
            centre.y,
            rotationAngle,
            font,
            bounds,
            lineSpacing,
            renderPassData.xCoordinateCalculator.getDataValue(renderPassData.isVerticalChart ? centre.y : centre.x),
            renderPassData.yCoordinateCalculator.getDataValue(renderPassData.isVerticalChart ? centre.x : centre.y),
            this.colorValue
        );
        if (
            label.rect.x < 0 ||
            label.rect.y < 0 ||
            label.rect.right > seriesViewRect.width ||
            label.rect.bottom > seriesViewRect.height
        ) {
            return undefined;
        }
        if (this.avoidOverlaps && placedRects.some(rect => rectsOverlap(rect, label.rect))) {
            return undefined;
        }
        return label;
    }

    /**
     * Traces the contour polylines, reusing the previous result when nothing which affects the
     * geometry has changed.
     * @remarks
     * The whole grid is always traced, never just the visible window. Tracing is the expensive part
     * of generating these labels, but clipping it to the view would make the polylines - and so the
     * anchors measured along them - change on every pan, so the labels would never settle. Tracing
     * everything once and caching it is both steadier and, over a pan or zoom, cheaper.
     */
    private getPolylines(dataSeries: UniformHeatmapDataSeries, levels: number[], stride: number): TContourPolyline[] {
        const signature = [dataSeries.id, dataSeries.changeCount, levels.join(","), stride].join("|");
        if (this.polylineCacheKey !== signature) {
            this.polylineCache = traceContours(this.zValues, levels, {
                iStart: 0,
                iEnd: dataSeries.arrayWidth - 1,
                jStart: 0,
                jEnd: dataSeries.arrayHeight - 1,
                strideX: stride,
                strideY: stride
            });
            this.polylineCacheKey = signature;
        }
        return this.polylineCache;
    }
}

/**
 * The fraction along a contour line of the anchor with the given ordinal:
 * 1/2, then 1/4, 3/4, then 1/8, 3/8, 5/8, 7/8, and so on.
 * @remarks
 * This is the whole anti-jitter mechanism.
 */
export const getAnchorFraction = (ordinal: number): number => {
    // Level of the binary subdivision this ordinal falls in, and its position within that level
    const level = Math.floor(Math.log2(ordinal + 1));
    const withinLevel = ordinal - (1 << level) + 1;
    return (2 * withinLevel + 1) / (1 << (level + 1));
};

/**
 * Works out where the labels on one traced contour line may go.
 * @remarks
 * Anchors are positions along the line's *grid-index* arc length, which is invariant under pan and
 * zoom, taken from {@link getAnchorFraction}. {@link labelSpacing} only decides how many of them to
 * use, so zooming adds and removes labels at the ends of that sequence instead of repositioning all
 * of them.
 * @ignore
 */
const buildTrace = (
    polyline: TContourPolyline,
    points: number[],
    text: string,
    textWidth: number,
    viewWidth: number,
    viewHeight: number,
    spacing: number,
    maxLabelsPerLine: number
): TLabelledTrace | undefined => {
    const indexLengths = getCumulativeLengths(polyline.points);
    const pixelLengths = getCumulativeLengths(points);
    const totalIndex = indexLengths[indexLengths.length - 1];
    const totalPixel = pixelLengths[pixelLengths.length - 1];
    if (totalIndex <= 0 || totalPixel < textWidth) return undefined;

    // How much of the line is on screen decides how many labels it wants, so that zooming into part
    // of a long contour still labels the part you can see.
    let visiblePixel = 0;
    for (let index = 2; index < points.length; index += 2) {
        const midX = (points[index] + points[index - 2]) / 2;
        const midY = (points[index + 1] + points[index - 1]) / 2;
        if (midX >= 0 && midX <= viewWidth && midY >= 0 && midY <= viewHeight) {
            visiblePixel += pixelLengths[index / 2] - pixelLengths[index / 2 - 1];
        }
    }
    if (visiblePixel < textWidth) return undefined;

    // Every anchor of one complete subdivision level, which is exactly the even lattice k / parts.
    // Taking a partial level instead would give the count asked for, but unevenly spaced.
    const parts = 1 << getAnchorLevel(totalPixel, visiblePixel, spacing, maxLabelsPerLine);

    const anchors: number[] = [];
    for (let ordinal = 0; ordinal < parts - 1; ordinal++) {
        const indexArc = getAnchorFraction(ordinal) * totalIndex;
        const { segment, t } = locateArc(indexLengths, indexArc);
        const point = pointOnSegment(points, segment, t);
        // Anchors on the off-screen part of the line are skipped, not shifted, so that panning
        // reveals and hides labels without moving the ones already on screen.
        if (point.x >= 0 && point.x <= viewWidth && point.y >= 0 && point.y <= viewHeight) {
            anchors.push(indexArc);
        }
    }
    if (anchors.length === 0) return undefined;

    return { level: polyline.level, text, points, pixelLengths, indexLengths, totalPixel, totalIndex, anchors };
};

/**
 * Chooses how many equal parts to divide a contour line into, as a power of two.
 * @param totalPixel pixel arc length of the whole line, including any part off screen
 * @param visiblePixel pixel arc length of the part inside the view rect
 * @param spacing target pixel distance between labels
 * @param maxLabelsPerLine cap on labels shown for the visible part of one line
 * @remarks
 * The result is a power of two because only complete subdivision levels are used: the first
 * `parts - 1` terms of {@link getAnchorFraction} are exactly the even lattice `k / parts`, whereas a
 * partial level would be lopsided - nine narrow gaps then two wide ones, for twelve labels. Powers
 * of two are also the only counts at which the even set nests inside the previous one, which is what
 * stops labels moving when the level changes mid-zoom.
 * @ignore
 */
export const getAnchorLevel = (
    totalPixel: number,
    visiblePixel: number,
    spacing: number,
    maxLabelsPerLine: number
): number => {
    // Fewest parts that still land an anchor inside the visible stretch. Rounded up, not to nearest,
    // or a line whose visible tenth needs ten parts could be given eight and come out unlabelled.
    const minParts = totalPixel / Math.max(visiblePixel, 1);
    const minLevel = Math.max(1, Math.ceil(Math.log2(Math.max(minParts, 2))));
    const wanted = Math.round(Math.log2(Math.max(totalPixel / spacing, 2)));
    let level = Math.min(MAX_ANCHOR_LEVEL, Math.max(minLevel, wanted));
    // Step back a level at a time while the visible stretch would carry more than the cap allows.
    // Never past minLevel: one label on a visible line beats honouring the cap exactly.
    const visibleFraction = Math.min(1, visiblePixel / totalPixel);
    while (level > minLevel && ((1 << level) - 1) * visibleFraction > maxLabelsPerLine) {
        level--;
    }
    return level;
};

/**
 * Chooses how coarsely to sample the grid when tracing. Cells smaller than a couple of pixels are
 * subsampled, since the resulting error in label position is invisible, and a hard cap on the cells
 * visited keeps very large heatmaps off the critical path. Quantised to a power of two so that a
 * zoom re-traces at most once per octave rather than continuously.
 * @ignore
 */
const getTraceStride = (
    arrayWidth: number,
    arrayHeight: number,
    pixelsPerColumn: number,
    pixelsPerRow: number
): number => {
    const cellSize = Math.min(Math.abs(pixelsPerColumn), Math.abs(pixelsPerRow));
    let stride = cellSize > 0 ? Math.max(1, MIN_TRACE_CELL_PIXELS / cellSize) : 1;
    const cells = ((arrayWidth / stride) * arrayHeight) / stride;
    if (cells > MAX_TRACE_CELLS) {
        stride *= Math.sqrt(cells / MAX_TRACE_CELLS);
    }
    return 1 << Math.ceil(Math.log2(stride));
};

/** Cumulative arc length of a flat `[x, y, ...]` polyline, one entry per point. @ignore */
const getCumulativeLengths = (points: number[]): number[] => {
    const lengths = [0];
    for (let index = 2; index < points.length; index += 2) {
        const dx = points[index] - points[index - 2];
        const dy = points[index + 1] - points[index - 1];
        lengths.push(lengths[lengths.length - 1] + Math.sqrt(dx * dx + dy * dy));
    }
    return lengths;
};

/**
 * Resolves an arc position into the segment containing it and the fraction along that segment.
 * Because a segment is a straight line in both index and pixel space, the same fraction locates the
 * same point in either, which is how an index-space anchor becomes a pixel position.
 * @ignore
 */
const locateArc = (lengths: number[], arcPos: number): { segment: number; t: number } => {
    let lo = 0;
    let hi = lengths.length - 1;
    while (lo < hi) {
        const mid = (lo + hi + 1) >>> 1;
        if (lengths[mid] <= arcPos) lo = mid;
        else hi = mid - 1;
    }
    const segment = Math.min(lo, lengths.length - 2);
    const span = lengths[segment + 1] - lengths[segment];
    return { segment, t: span > 0 ? (arcPos - lengths[segment]) / span : 0 };
};

/** @ignore */
const pointOnSegment = (points: number[], segment: number, t: number): { x: number; y: number } => {
    const x0 = points[segment * 2];
    const y0 = points[segment * 2 + 1];
    return { x: x0 + t * (points[segment * 2 + 2] - x0), y: y0 + t * (points[segment * 2 + 3] - y0) };
};

/** The point at the given arc position along a flat `[x, y, ...]` polyline. @ignore */
const interpolateAlong = (points: number[], lengths: number[], arcPos: number): { x: number; y: number } => {
    const { segment, t } = locateArc(lengths, arcPos);
    return pointOnSegment(points, segment, t);
};

/**
 * Axis aligned bounding box of a rect rotated about its own centre. The label rect is always built
 * centred on its rotation centre, so the box follows in closed form.
 * @ignore
 */
const getRotatedBoundingBox = (rect: Rect, centre: Point, angle: number): Rect => {
    const sin = Math.abs(Math.sin(angle));
    const cos = Math.abs(Math.cos(angle));
    const width = rect.width * cos + rect.height * sin;
    const height = rect.width * sin + rect.height * cos;
    return new Rect(centre.x - width / 2, centre.y - height / 2, width, height);
};

/** @ignore */
const rectsOverlap = (first: Rect, second: Rect): boolean =>
    first.left < second.right && second.left < first.right && first.top < second.bottom && second.top < first.bottom;
